image: "python:latest"

stages:
  - build
  - deploy

docker_build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: []
  script:
    - mkdir -p /root/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_JOB_TOKEN\"}}}" > /root/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile $DOCKER_PROXY --destination $CI_REGISTRY_IMAGE --verbosity warn
  only:
    - master

deploy:
  stage: deploy
  image: boxboat/kubectl
  environment:
    name: production
    url: http://${CI_PROJECT_PATH_SLUG}.kubernetes-public.it.liu.se/
  before_script: []
  script:
    - kubectl delete secret regcred || true
    - kubectl create secret docker-registry regcred --docker-server="$CI_REGISTRY" --docker-username="$CI_DEPLOY_USER" --docker-password="$CI_DEPLOY_PASSWORD"
    - |
      # Deploy environment with kubectl apply

      kubectl apply -f - <<EOF
      ---
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        annotations:
          se.liu.gitlab/commit: $CI_COMMIT_SHA
          app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
          app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
        labels:
          app: ${CI_PROJECT_PATH_SLUG}
          environment: $CI_ENVIRONMENT_SLUG
        name: ${CI_PROJECT_PATH_SLUG}
      spec:
        replicas: 1
        revisionHistoryLimit: 1
        selector:
          matchLabels:
            app: ${CI_PROJECT_PATH_SLUG}
            environment: $CI_ENVIRONMENT_SLUG
        template:
          metadata:
            annotations:
              prometheus.io/port: "4567"
              prometheus.io/scrape: "true"
              app.gitlab.com/app: $CI_PROJECT_PATH_SLUG
              app.gitlab.com/env: $CI_ENVIRONMENT_SLUG
            labels:
              commit: $CI_COMMIT_SHA
              app: ${CI_PROJECT_PATH_SLUG}
              environment: $CI_ENVIRONMENT_SLUG
          spec:
            imagePullSecrets:
            - name: regcred
            containers:
            - env:
              - name: http_proxy
                value: http://squid-proxy.kube-system.svc:3128/
              - name: https_proxy
                value: http://squid-proxy.kube-system.svc:3128/
              image: $CI_REGISTRY_IMAGE
              imagePullPolicy: Always
              name: ${CI_PROJECT_PATH_SLUG}
              ports:
              - containerPort: 3000
                protocol: TCP
              readinessProbe:
                tcpSocket:
                  port: 3000
              resources:
                limits:
                  cpu: 100m
                  memory: 80Mi
                requests:
                  cpu: 15m
                  memory: 42Mi
      ---
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          commit: $CI_COMMIT_SHA
          app: ${CI_PROJECT_PATH_SLUG}
          environment: $CI_ENVIRONMENT_SLUG
        name: ${CI_PROJECT_PATH_SLUG}
      spec:
        ports:
        - name: web
          port: 80
          protocol: TCP
          targetPort: 3000
        selector:
          app: ${CI_PROJECT_PATH_SLUG}
          environment: $CI_ENVIRONMENT_SLUG
        type: ClusterIP
      EOF
    - |
      # Deploy production ingress only on the production environment

      [ "$CI_ENVIRONMENT_SLUG" == "production" ] && kubectl apply -f - <<EOF || true
      ---
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: ${CI_PROJECT_PATH_SLUG}
        annotations:
          kubernetes.io/ingress.class: nginx-public
        labels:
          app: ${CI_PROJECT_PATH_SLUG}
          environment: $CI_ENVIRONMENT_SLUG
      spec:
        rules:
        - host: ${CI_PROJECT_PATH_SLUG}.kubernetes-public.it.liu.se
          http:
            paths:
            - backend:
                serviceName: ${CI_PROJECT_PATH_SLUG}
                servicePort: 80
              path: /
      EOF
  variables:
    GIT_STRATEGY: none
